parameters:
#    poe_core.example.class: Poe\CoreBundle\Example

services:
    # Item
    poe_core_item_admin:
        class: Poe\CoreBundle\Admin\ItemAdmin
        arguments: [ @poe_core.item_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.item_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\Item ]
        parent: msi_cmf.manager

    # ItemType
    poe_core_item_type_admin:
        class: Poe\CoreBundle\Admin\ItemTypeAdmin
        arguments: [ @poe_core.item_type_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.item_type_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ItemType ]
        parent: msi_cmf.manager

    # ExplicitMod
    poe_core_explicit_mod_admin:
        class: Poe\CoreBundle\Admin\ExplicitModAdmin
        arguments: [ @poe_core.explicit_mod_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.explicit_mod_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ExplicitMod ]
        parent: msi_cmf.manager

    # ItemExplicitMod
    poe_core_item_explicit_mod_admin:
        class: Poe\CoreBundle\Admin\ItemExplicitModAdmin
        arguments: [ @poe_core.item_explicit_mod_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.item_explicit_mod_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ItemExplicitMod ]
        parent: msi_cmf.manager

    # ImplicitMod
    poe_core_implicit_mod_admin:
        class: Poe\CoreBundle\Admin\ImplicitModAdmin
        arguments: [ @poe_core.implicit_mod_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.implicit_mod_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ImplicitMod ]
        parent: msi_cmf.manager

    # ItemImplicitMod
    poe_core_item_implicit_mod_admin:
        class: Poe\CoreBundle\Admin\ItemImplicitModAdmin
        arguments: [ @poe_core.item_implicit_mod_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.item_implicit_mod_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ItemImplicitMod ]
        parent: msi_cmf.manager

    # Property
    poe_core_property_admin:
        class: Poe\CoreBundle\Admin\PropertyAdmin
        arguments: [ @poe_core.property_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.property_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\Property ]
        parent: msi_cmf.manager

    # ItemProperty
    poe_core_item_property_admin:
        class: Poe\CoreBundle\Admin\ItemPropertyAdmin
        arguments: [ @poe_core.item_property_manager ]
        parent: msi_cmf.admin
        tags:
            - { name: msi.admin }

    poe_core.item_property_manager:
        class: %msi_cmf.manager.class%
        arguments: [ Poe\CoreBundle\Entity\ItemProperty ]
        parent: msi_cmf.manager
