parameters:
#    poe_user.example.class: Poe\UserBundle\Example

services:
#    poe_user.example:
#        class: %poe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
